### ISSUE TITLE
Add support for zero app downtime when making route config changes

### ISSUE THREAD

**Issue by dektlong** [spring-cloud-services-samples/animal-rescue#14]
example scenario

I want to add a ratelimit filter to "path": "/rescue/**"

applying this change to my gateway config should happen in a "blue/green" way so at no point during this change users will experience traffic disruption at [my-gw-host].[my-domain]/rescue

thank you

**Comment by LittleBaiBai** [comment]
Hi @dektlong, thanks for raising this issue. We added support for dynamic route update in SCG-VT 1.0.6. With [this new API endpoint](https://docs.pivotal.io/spring-cloud-gateway/1-0/configuring-routes.html#updating-routes-via-api), bound app routes can be updated without any traffic disruption. You may also check out the `dynamic_route_config_update` command in `cf_deploy` script.

**Comment by dektlong** [comment]
thank you the update. I will check this out!
