### ISSUE TITLE
Document how to deploy animal rescue to Kubernetes

### ISSUE THREAD

**Issue by ojhughes** [spring-cloud-services-samples/animal-rescue#32]
Provide instructions and example manifest on how to deploy
animal rescue and a Spring Cloud Gateway to a Kubernetes cluster

**Comment by mikegehard** [comment]
@ojhughes Looks like they are in there now?

https://github.com/spring-cloud-services-samples/animal-rescue#deploy-to-kubernetes

Curious if I can close this?

**Comment by fombico** [comment]
Instructions to deploy on k8s are present. Closing this issue.
