### ISSUE TITLE
Adapt the sample app to work with SCG4k8s

### ISSUE THREAD

**Issue by LittleBaiBai** [spring-cloud-services-samples/animal-rescue#38]
To demonstrate SCG4k8s, we need to add a new script to deploy animal-rescue on k8s and set up routes through binding dynamic route registering (https://github.com/pivotal-cf/spring-cloud-gateway-service/issues/874).

**Comment by csterwa** [comment]
@LittleBaiBai does this now work with dynamic updates? Should I just apply this again into my environment?

**Comment by LittleBaiBai** [comment]
@csterwa Dynamic update story in SCG4k8s is now back in the "In Progress" column due to a design flaw we found recently. Once we fix that in SCG4k8s, what we have in animal-rescue should just work. In the meantime, you can explicitly list out service uris like in `gateway-demo.yaml`.
