### ISSUE TITLE
Move around k8s & TAS configuration files to show off separate app dev life cycles

### ISSUE THREAD

**Issue by csterwa** [spring-cloud-services-samples/animal-rescue#69]
Currently, we have all of the k8s related custom resource files for kustomize in a single folder. This means that both of the apps and the gateway are configured in the same folder and doesn't show how we can deploy each on their own as we do with the TAS versions of these configuration today. I want to recommend the following:

* Move frontend and backend app related custom resource files to their respective directories and create a kustomize file for each
* Make a directory named `gateway` that both the TAS gateway configuration JSON and the instance related custom resource files can be put, including secrets file locations
* Create a kustomize file that is at top-level directory and is able to deploy everything at once as we do today
* Move contents of ./k8s/deploy_to_k8s.md into main README

**Comment by shrutiyer** [comment]
https://github.com/spring-cloud-services-samples/animal-rescue/pull/71 fulfills this issue
