### ISSUE TITLE
Document how to set up SSO with either Google or Okta

### ISSUE THREAD

**Issue by mikegehard** [spring-cloud-services-samples/animal-rescue#84]
As a developer wanting to try out Spring Cloud Gateway SSO
I need to set up an SSO provider

These documents should link out to the provider setup docs so that we don't get out of date
and tell the user how to configure.

**Comment by alek-sys** [comment]
There is  [this](https://docs.pivotal.io/scg-k8s/1-0/sso-setup-guide.html) document, specifically for Okta + Animal Rescue (but could be any app really). Does it help at all?

**Comment by mikegehard** [comment]
Yep that's perfect...thanks @alek-sys.

I'll add a link to that doc as the solution for this issue.
