### ISSUE TITLE
Sign out of application

### ISSUE THREAD

**Issue by csterwa** [spring-cloud-services-samples/animal-rescue#9]
Potential Adopter wants to sign out of application so that they feel safe that their session has ended

GIVEN potential adopter is signed into Animal Rescue application
WHEN they click "Sign Out" link/button
THEN they are no longer signed into application

**Comment by spikymonkey** [comment]
We also want to add CSRF protection to the `/scg-logout` endpoint on Gateway to prevent random clients from ending users' sessions.

There's more discussion [in this Slack thread](https://pivotal.slack.com/archives/C064Q28L9/p1582646009073500), but the TL;DR is that we want to return the CSRF token in a cookie to the client, and then there'll be some extra work on the client side to make sure the token is picked up and sent in the logout request.

**Comment by spikymonkey** [comment]
I think I have this working now. I'll ask @alek-sys for a sanity check in the morning as I still have a few outstanding questions, but all being well should be able to merge this in very soon.

**Comment by spikymonkey** [comment]
@LittleBaiBai and I spoke with @csterwa today and we realised that we don't need to do the sign out of UAA part. So what we have now is nearly enough, we just need to fix some problems with running in the local mode, and also figure out how to test this properly in an AT.

**Comment by alek-sys** [comment]
@spikymonkey do you mind adding a short summary of your conversation here? I'm curious why we don't need to log out from UAA anymore.

**Comment by spikymonkey** [comment]
@LittleBaiBai made the excellent point that this is not what would happen with other SSO systems. E.g. signing out of WorkDay does not sign us out of Okta, and re-authenticating would happen immediately as it does for us in Animal Rescue now

**Comment by alek-sys** [comment]
Thanks, very good point. I just remember @csterwa saying on IPM "I just want it to log out from UAA" 🙂 Also, SCDF does that, so we need to be aware of different behaviour.

**Comment by spikymonkey** [comment]
Sorry, didn't mean to close this
